apiVersion: v1
kind: Service
metadata:
  labels:
    service: travelgram-restapi-feed
  name: travelgram-restapi-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: travelgram-restapi-feed