apiVersion: v1
kind: Service
metadata:
  labels:
    service: travelgram-frontend
  name: travelgram-frontend
spec:
  type: LoadBalancer
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: travelgram-frontend
